### ISSUE TITLE
brnn example error

### ISSUE THREAD

**Issue by tuming1990** [EderSantana/seya#22]
@EderSantana 

Thank you for the seya code. I want to use the bidirectional RNN, but I got an error when I ran the imdb_brnn.py in the examples.  It seems like a simple error but I still don't know how to fix it. Sorry I'm new to keras. Here is the error detail. Thanks!

```python
Original exception was:
Traceback (most recent call last):
  File "/home/ming-ubuntu/Downloads/pycharm-community-5.0.4/helpers/pydev/pydevd.py", line 2411, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/ming-ubuntu/Downloads/pycharm-community-5.0.4/helpers/pydev/pydevd.py", line 1802, in run
    launch(file, globals, locals)  # execute the script
  File "/home/ming-ubuntu/Downloads/seya-master/examples/imdb_brnn.py", line 59, in <module>
    model.add(brnn)  # try using another Bidirectional RNN inside the Bidirectional RNN. Inception meets callback hell.
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/containers.py", line 70, in add
    self.layers[-1].set_previous(self.layers[-2])
  File "/usr/local/lib/python2.7/dist-packages/seya-0.1.0-py2.7.egg/seya/layers/recurrent.py", line 55, in set_previous
    self.forward.set_previous(layer, connection_map)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 146, in set_previous
    assert layer.output_shape == self.input_shape, ('Cannot connect layers without resetting weights: ' +
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 212, in input_shape
    raise Exception('Layer is not connected. Did you forget to set "input_shape"?')
Exception: Layer is not connected. Did you forget to set "input_shape"?
```

**Comment by EderSantana** [comment]
Conversation related to #21
Let us move over there.

I have to review brnn due to the recent API changes in Keras. But I believe Keras now supports bidirectional RNNs out of the box doesn't it? You could use two separate RNNs in a graph and one of them using `go_backwards` flag. 

Anyways, I'll review the solution we have over here soon. Thanks for the issue!

**Comment by Thanabhat** [comment]
Quickly solve the problem by adding `input_shape` to recurrent layer

```
lstm = LSTM(output_dim=64, input_shape=(maxlen, 128))
gru = GRU(output_dim=64, input_shape=(maxlen, 128))
```

128 is output dimensions of a previous embedding layer
