### ISSUE TITLE
Winner take all autoencoder update

### ISSUE THREAD

**Issue by zoli333** [EderSantana/seya#45]
Hi

I want to update your WinnerTakeAll layer to work with the new keras.

'''
THEANO_FLAGS=device=gpu7,floatX=float32,blas.ldflags="-L/usr/lib/ -lblas" python wta.py

'''
from __future__ import print_function
from keras.models import Sequential
from keras.layers import Dense, Dropout, Layer, Activation
from keras.datasets import mnist
from keras import backend as K
from keras.utils import np_utils
from keras import backend as K
from keras.layers.core import Layer
from theano import tensor as T  # , scan
from keras.layers import Input, Dense, Convolution2D, MaxPooling2D, UpSampling2D
from keras.models import Model
from keras import backend as K
from keras.engine.topology import Layer
import numpy as np
from keras.utils import np_utils
from keras import initializations

def scale_norm(X):
    X = X - X.min()
    scale = (X.max() - X.min())
    return X / scale

def grid2d(X, example_width=False, display_cols=False, pad_row=1,
           pad_col=1, rescale=True):
    """Display weights in a nice grid
    This function assumes that each row of the X is an image weight to be
    resized to a square. After that it creates a 2D grid with with all
    the squares.
    Parameters
    ----------
    X : `numpy.array`
        array with each filter to be transformed to an image on the rows
    example_width: int
        defines the width of the images in the rows X if they are
        not square
    display_cols: bool
    pad_row: int
        integer number of pixels between up/down neighbors
    pad_col: int
        integer number of pixels between left/right neighbors
    Adapted from https://github.com/martinblom/py-sparse-filtering
    """
    m, n = X.shape
    if not example_width:
        example_width = int(np.round(np.sqrt(n)))
    example_height = n//example_width
    # Compute number of items to display
    if not display_cols:
        display_cols = int(np.sqrt(m))
    display_rows = int(np.ceil(m/display_cols))
    # Setup blank display
    display_array = -np.ones((pad_row+display_rows * (example_height+pad_row),
                              pad_col+display_cols * (example_width+pad_col)))
    # Copy each example into a patch on the display array
    curr_ex = 0
    for j in range(display_rows):
        for i in range(display_cols):
            if curr_ex >= m:
                break
            # Copy the patch
            # Get the max value of the patch
            max_val = abs(X[curr_ex, :]).max()
            i_inds = example_width*[pad_row+j * (example_height+pad_row)+q for q in range(example_height)]
            j_inds = [pad_col+i * (example_width+pad_col)+q
                      for q in range(example_width)
                      for nn in range(example_height)]
            try:
                newData = (X[curr_ex, :].reshape((example_height,
                                                  example_width))).T/max_val
            except:
                raise ValueError("expected {}, got {}".format(X[curr_ex, :].shape), (example_height, example_width))
            display_array[i_inds, j_inds] = newData.flatten()
            curr_ex += 1
        if curr_ex >= m:
            break
    visual = (display_array - display_array.min()) / (display_array.max() - display_array.min())
    visual = np.nan_to_num(visual)
    ret = visual if rescale else display_array
    ret = (255*ret).astype(np.uint8)
    return ret

def img_grid(X, rows_cols=None, rescale=True):
    """Image Grid: modified from jbornschein/draw
    Parameters:
    ===========
    X : np.array, images (samples, channels, height, width)
    rows_cols : list, grid dimensions (rows, cols)
    rescale : bool
    Returns:
    ========
    I : np.array, grid image
    """
    N, channels, height, width = X.shape
    
    if rows_cols is None:
        sroot = np.sqrt(X.shape[0])
        cols = int(np.ceil(sroot))
        rows = int(np.floor(sroot)) + 1
    else:
        rows, cols = rows_cols
    
    total_height = int(rows * height + rows - 1)
    total_width = int(cols * width + cols - 1)
    
    if rescale:
        X = scale_norm(X)
    
    I = np.zeros((channels, total_height, total_width))
    I.fill(1)
    
    for i in xrange(N):
        r = i // cols
        c = i % cols
        
        if rescale:
            this = X[i]
        else:
            this = scale_norm(X[i])
        
        offset_y, offset_x = r*height+r, c*width+c
        I[0:channels, offset_y:(offset_y+height), offset_x:(offset_x+width)] = this
    
    I = (255*I).astype(np.uint8)
    if(channels == 1):
        out = I.reshape((total_height, total_width))
    else:
        out = np.dstack(I).astype(np.uint8)
    return out

class WinnerTakeAll2D(Layer):
	"""Spatial Winner-Take-All
	ref: Winner-Take-All Autoencoders by  Alireza Makhzani, Brendan Frey
	Parameters:
	-----------
	spatial: int, controls spatial sparsity, defines maximum number of non zeros
		in a spatial map
	lifetime, int, controls lifetime sparsity, defines maximum number of non
		zeros in a dimension throughout the batches
	n_largest: int, global sparsity, defines maximum number of non zeros in the
		output tensor.
	previous_mode: bool, flag to use legacy behavior of this layer
	NOTE:
	=====
	This is a Theano only layer
	"""
	def __init__(self, spatial=1, lifetime=5, **kwargs):
		self.spatial = spatial
		self.lifetime = lifetime
		super(WinnerTakeAll2D, self).__init__(**kwargs)
	
	def call(self, x, mask=None):
		#  basic wta, kept every maximum on all of the feature in all of the batches
		# it depends hardly by the number of features in the layers
		#M = K.max(x, axis=(2, 3), keepdims=True)
		#R = K.switch(K.equal(x, M), x, 0.)
		#return R
		
               # Spatial and lifetime
		# maxes across minibatch (spatial is now just 1, keep just 1 value in minibatch across each feature map so in 100 minibatch size, and 32 feature size, there wull be 100 maximal values)
		M = K.max(x, axis=(1, 2, 3), keepdims=True)
		R = K.switch(K.equal(x, M), x, 0.)
		
		# lifetime drop (drop "lifetime" amount of maximum from the minibatch, across each feature map)
		s = T.sort(R.flatten())
		nl = s[-self.lifetime]
		R = T.switch(T.ge(R, nl), R, 0.)
		
		return R
	
	def get_output_shape_for(self, input_shape):
		#shape = tuple(input_shape)
		#print(shape)
		#return tuple(shape)
		shape = list(input_shape)
		return tuple(shape)
	

# global parameters

batch_size = 100
nb_classes = 10
nb_epoch = 20

# the data, shuffled and split between train and test sets
(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train.reshape(len(X_train),1,28,28)
#X_train = X_train[:1000]
X_test = X_test.reshape(len(X_test), 1, 28, 28)
X_test = X_test[:100]
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255
print(X_train.shape, 'train samples')
print(X_test.shape, 'test samples')

def my_init(shape, name=None):
    return initializations.normal(shape, scale = 0.001, name = name)

enc = Sequential()
enc.add(Convolution2D(64, 5, 5,border_mode='same',activation='relu',init=my_init,input_shape=(1,28,28)))
enc.add(Convolution2D(64, 5, 5,border_mode='same',activation='relu',init=my_init))
enc.add(Convolution2D(64, 5, 5,border_mode='same',activation='relu',init=my_init))
enc.add(WinnerTakeAll2D(spatial=1,lifetime=20))
poolshape = enc.output_shape[1:]

dec = Sequential()
dec.add(Convolution2D(1, 11, 11,border_mode='same',input_shape=poolshape))

model = Sequential()
model.add(enc)
model.add(dec)

#sgd = SGD(lr=0.001, decay = 1e-06, momentum=0.9, nesterov=True)
model.compile(loss='mse', optimizer = 'adagrad')
model.fit(X_train, X_train, batch_size=batch_size, nb_epoch=nb_epoch, verbose=1)

# TESTING PHASE
#  remove the winnertakeall (spatial) layer from the model
model.layers[0].layers.pop()

import matplotlib.pyplot as plt
decoded_imgs = model.predict(X_test)

#Visualize encoder
W = np.asarray(K.eval(enc.layers[0].W))
W = W.reshape((64, -1))
I = grid2d(W)
plt.imshow(I,cmap='gray')
plt.savefig('enc1.png')

#Visualize encoder
W = np.asarray(K.eval(enc.layers[1].W))
W = W.reshape((64, -1))
I = grid2d(W)
plt.imshow(I,cmap='gray')
plt.savefig('enc2.png')

#Visualize decoder
W = np.asarray(K.eval(dec.layers[0].W))
W = W.reshape((64, -1))
I = grid2d(W)
plt.imshow(I,cmap='gray')
plt.savefig('dec1.png')

n = 10
plt.figure(figsize=(20, 4))
for i in range(n):
	# display original
	ax = plt.subplot(2, n, i+1)
	plt.imshow(X_test[i].reshape(28, 28))
	plt.gray()
	ax.get_xaxis().set_visible(False)
	ax.get_yaxis().set_visible(False)
	
	# display reconstruction
	ax = plt.subplot(2, n, i + n + 1)
	plt.imshow(scale_norm(decoded_imgs[i].reshape(28, 28)))
	plt.gray()
	ax.get_xaxis().set_visible(False)
	ax.get_yaxis().set_visible(False)

plt.savefig('reconstruct.png')

I implemented the Spatial + lifetime winner take all code based on the article:
http://arxiv.org/pdf/1409.2752v2.pdf
My question is my winnertakeall function correct? And in the feed-forward case is this function returns the masked x, but more importantly is it return the masked filters in the backward case? If not how can I set this.

Thank you

**Comment by EderSantana** [comment]
Hi @zoli333 tkx for your interest in Seya.
Please consider making a pull request with your modifications to the keras1 branch.

I think that I interchanged the functions because I named the behavior in the wrong way. But please, if you debug that let me know.

**Comment by zoli333** [comment]
Hi
These are my modifications to implement just spatial + lifetime sparsity. Sorry I don't know how to use github, so I am attaching my code.

[wta.zip](https://github.com/EderSantana/seya/files/417794/wta.zip)

Could you help. It runs fine with the iterations, but when autoencoder.predict(X_test) is called, the program throws the following error:
model2.predict(X_test,X_test)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 648, in predict
    return self.model.predict(x, batch_size=batch_size, verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1180, in predict
    batch_size=batch_size, verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 869, in _predict_loop
    batches = make_batches(nb_sample, batch_size)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 281, in make_batches
    nb_batch = int(np.ceil(size / float(batch_size)))
TypeError: only length-1 arrays can be converted to Python scalars
>>> model2.predict(X_tes)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'X_tes' is not defined
>>> model2.predict(X_test)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 648, in predict
    return self.model.predict(x, batch_size=batch_size, verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1180, in predict
    batch_size=batch_size, verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 879, in _predict_loop
    batch_outs = f(ins_batch)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 657, in __call__
    return self.function(*inputs)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 879, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 866, in __call__
    self.fn() if output_subset is None else\
IndexError: index out of bounds
Apply node that caused the error: Subtensor{int64}(SortOp{quicksort, None}.0, Constant{-20})
Toposort index: 29
Inputs types: [TensorType(float32, 4D), Scalar(int64)]
Inputs shapes: [(10, 64, 28, 28), ()]
Inputs strides: [(200704, 3136, 112, 4), ()]
Inputs values: ['not shown', -20]
Outputs clients: [[InplaceDimShuffle{x,0,1,2}(Subtensor{int64}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 307, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 511, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 569, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 150, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "<stdin>", line 40, in call

I appreciate your help
